export const userTags = [
    // Languages
    { value: "javascript", label: "JavaScript" },
    { value: "typescript", label: "TypeScript" },
    { value: "python", label: "Python" },
    { value: "golang", label: "Go" },
    { value: "rust", label: "Rust" },
    { value: "java", label: "Java" },
    { value: "csharp", label: "C#" },
    { value: "php", label: "PHP" },
    { value: "ruby", label: "Ruby" },
    { value: "swift", label: "Swift" },

    // Frontend
    { value: "react", label: "React" },
    { value: "nextjs", label: "Next.js" },
    { value: "vue", label: "Vue.js" },
    { value: "angular", label: "Angular" },
    { value: "svelte", label: "Svelte" },
    { value: "html", label: "HTML" },
    { value: "css", label: "CSS" },
    { value: "tailwindcss", label: "Tailwind CSS" },
    { value: "vite", label: "Vite" },
    { value: "web-components", label: "Web Components" },

    // Backend
    { value: "nodejs", label: "Node.js" },
    { value: "express", label: "Express.js" },
    { value: "nestjs", label: "NestJS" },
    { value: "graphql", label: "GraphQL" },
    { value: "rest-api", label: "REST API" },
    { value: "grpc", label: "gRPC" },
    { value: "websockets", label: "WebSockets" },
    { value: "authentication", label: "Authentication" },
    { value: "authorization", label: "Authorization" },
    { value: "api-design", label: "API Design" },

    // Database
    { value: "postgresql", label: "PostgreSQL" },
    { value: "mysql", label: "MySQL" },
    { value: "mongodb", label: "MongoDB" },
    { value: "redis", label: "Redis" },
    { value: "sqlite", label: "SQLite" },
    { value: "elasticsearch", label: "Elasticsearch" },
    { value: "orm", label: "ORM" },
    { value: "database-design", label: "Database Design" },
    { value: "query-optimization", label: "Query Optimization" },
    { value: "caching", label: "Caching" },

    // Cloud & DevOps
    { value: "docker", label: "Docker" },
    { value: "kubernetes", label: "Kubernetes" },
    { value: "aws", label: "AWS" },
    { value: "azure", label: "Azure" },
    { value: "gcp", label: "Google Cloud" },
    { value: "terraform", label: "Terraform" },
    { value: "github-actions", label: "GitHub Actions" },
    { value: "ci-cd", label: "CI/CD" },
    { value: "serverless", label: "Serverless" },
    { value: "linux", label: "Linux" },

    // AI
    { value: "ai", label: "Artificial Intelligence" },
    { value: "machine-learning", label: "Machine Learning" },
    { value: "deep-learning", label: "Deep Learning" },
    { value: "generative-ai", label: "Generative AI" },
    { value: "llms", label: "LLMs" },
    { value: "rag", label: "RAG" },
    { value: "ai-agents", label: "AI Agents" },
    { value: "prompt-engineering", label: "Prompt Engineering" },
    { value: "embeddings", label: "Embeddings" },
    { value: "vector-database", label: "Vector Database" },

    // Architecture
    { value: "system-design", label: "System Design" },
    { value: "microservices", label: "Microservices" },
    { value: "distributed-systems", label: "Distributed Systems" },
    { value: "event-driven", label: "Event Driven" },
    { value: "message-queues", label: "Message Queues" },
    { value: "architecture", label: "Software Architecture" },
    { value: "scalability", label: "Scalability" },
    { value: "high-availability", label: "High Availability" },
    { value: "fault-tolerance", label: "Fault Tolerance" },
    { value: "design-patterns", label: "Design Patterns" },

    // Quality
    { value: "testing", label: "Testing" },
    { value: "performance", label: "Performance" },
    { value: "security", label: "Security" },
    { value: "observability", label: "Observability" },
    { value: "monitoring", label: "Monitoring" },
    { value: "logging", label: "Logging" },
    { value: "debugging", label: "Debugging" },
    { value: "refactoring", label: "Refactoring" },
    { value: "clean-code", label: "Clean Code" },
    { value: "code-quality", label: "Code Quality" },

    // Engineering
    { value: "case-study", label: "Case Study" },
    { value: "best-practices", label: "Best Practices" },
    { value: "tutorial", label: "Tutorial" },
    { value: "engineering-culture", label: "Engineering Culture" },
    { value: "developer-experience", label: "Developer Experience" },
    { value: "developer-tools", label: "Developer Tools" },
    { value: "open-source", label: "Open Source" },
    { value: "product-engineering", label: "Product Engineering" },
    { value: "career", label: "Career" },
    { value: "interview", label: "Interview" },
] as const;



// tag mapping with alias
type TagAliasMap = Record<string, string[]>;

export const TagsAlias: TagAliasMap = {
    // =========================
    // Languages
    // =========================
    javascript: [
        "js",
        "javascript",
        "ecmascript",
        "es6",
        "es2015",
        "es2020",
        "es2021",
        "es2022",
        "es2023",
        "es2024",
        "vanilla js",
        "vanilla javascript",
        "modern javascript",
        "js programming",
        "javascript programming",
        "javascript development",
        "async javascript",
        "javascript async",
        "js tricks",
    ],

    typescript: [
        "ts",
        "typescript",
        "typed javascript",
        "tsconfig",
        "type safety",
        "type-safe javascript",
        "typescript generics",
        "generics",
        "interfaces",
        "typescript types",
        "ts types",
        "typescript compiler",
        "tsx",
    ],

    python: [
        "py",
        "python3",
        "python 3",
        "cpython",
        "python programming",
        "python development",
        "python scripting",
        "pythonic",
        "pip",
        "virtualenv",
        "venv",
        "poetry",
        "pydantic",
    ],

    golang: [
        "go",
        "go lang",
        "golang",
        "go programming",
        "go programming language",
        "goroutines",
        "channels",
        "go modules",
        "gomod",
        "gin golang",
        "fiber golang",
    ],

    rust: [
        "rustlang",
        "rust programming",
        "rust programming language",
        "cargo",
        "rust cargo",
        "ownership",
        "borrowing",
        "rust memory safety",
        "rust async",
        "tokio",
    ],

    java: [
        "java se",
        "java ee",
        "jvm",
        "java virtual machine",
        "java programming",
        "java development",
        "openjdk",
        "jdk",
        "jre",
        "spring java",
        "spring boot java",
    ],

    csharp: [
        "c#",
        "c-sharp",
        "csharp",
        "dotnet",
        ".net",
        ".net core",
        "dotnet core",
        "asp.net",
        "aspnet",
        "c# programming",
        "csharp programming",
        "blazor",
    ],

    php: [
        "php7",
        "php8",
        "php programming",
        "php development",
        "php scripting",
        "laravel",
        "laravel php",
        "symfony",
        "composer php",
    ],

    ruby: [
        "ruby lang",
        "ruby language",
        "ruby programming",
        "ruby on rails",
        "rails",
        "ror",
        "rb",
        "rails development",
    ],

    swift: [
        "swiftui",
        "swift ui",
        "swift programming",
        "ios swift",
        "apple swift",
        "swift language",
        "xcode swift",
    ],

    // =========================
    // Frontend
    // =========================
    react: [
        "reactjs",
        "react.js",
        "react js",
        "react",
        "react hooks",
        "hooks",
        "jsx",
        "tsx",
        "react components",
        "react component",
        "react state",
        "react state management",
        "react context",
        "react router",
        "react query",
        "tanstack query",
        "redux",
        "redux toolkit",
        "zustand",
        "recoil",
    ],

    nextjs: [
        "next.js",
        "next js",
        "nextjs",
        "next",
        "next js app router",
        "app router",
        "next app router",
        "pages router",
        "next server components",
        "next.js ssr",
        "next ssr",
        "nextjs ssr",
        "next middleware",
        "next api routes",
        "next route handlers",
        "vercel next",
    ],

    vue: [
        "vuejs",
        "vue.js",
        "vue js",
        "vue3",
        "vue 3",
        "vue composition api",
        "composition api",
        "vue options api",
        "pinia",
        "vue router",
    ],

    angular: [
        "angularjs",
        "angular 2",
        "angular2+",
        "angular framework",
        "angular frontend",
        "ng",
        "typescript angular",
        "rxjs angular",
    ],

    svelte: [
        "sveltejs",
        "svelte.js",
        "svelte js",
        "sveltekit",
        "svelte kit",
        "svelte 5",
    ],

    html: [
        "html5",
        "html 5",
        "markup",
        "semantic html",
        "html tags",
        "html elements",
        "web markup",
    ],

    css: [
        "css3",
        "css 3",
        "stylesheets",
        "stylesheet",
        "css styling",
        "cascading style sheets",
        "responsive css",
        "responsive design",
        "css layout",
        "flexbox",
        "css grid",
    ],

    tailwindcss: [
        "tailwind",
        "tailwind css",
        "tailwindcss",
        "utility-first css",
        "utility css",
        "tailwind ui",
        "tailwind v3",
        "tailwind v4",
    ],

    vite: [
        "vitejs",
        "vite.js",
        "vite bundler",
        "vite build tool",
        "vite dev server",
        "vite config",
    ],

    "web-components": [
        "custom elements",
        "custom element",
        "shadow dom",
        "shadow root",
        "web component",
        "web components",
        "native web components",
    ],

    // =========================
    // Backend
    // =========================
    nodejs: [
        "node",
        "node.js",
        "node js",
        "nodejs",
        "node backend",
        "node runtime",
        "node runtime environment",
        "npm",
        "npx",
        "node server",
        "node backend development",
    ],

    express: [
        "expressjs",
        "express.js",
        "express js",
        "express",
        "express middleware",
        "express server",
        "express api",
        "express backend",
    ],

    nestjs: [
        "nest.js",
        "nest js",
        "nestjs",
        "nest framework",
        "nestjs backend",
        "nestjs api",
        "nestjs architecture",
    ],

    graphql: [
        "gql",
        "graphql api",
        "graphql schema",
        "graphql query",
        "graphql queries",
        "graphql mutations",
        "graphql subscriptions",
        "apollo graphql",
        "apollo server",
        "graphql federation",
    ],

    "rest-api": [
        "rest",
        "rest api",
        "restful api",
        "rest apis",
        "restful services",
        "rest endpoints",
        "http api",
        "http apis",
        "json api",
        "api endpoints",
        "web api",
    ],

    grpc: [
        "grpc",
        "grpc api",
        "grpc service",
        "protocol buffers",
        "protobuf",
        "proto",
        "remote procedure call",
        "rpc",
        "grpc-web",
    ],

    websockets: [
        "websocket",
        "websockets",
        "ws protocol",
        "socket.io",
        "socket io",
        "real-time communication",
        "realtime communication",
        "real time",
        "bidirectional communication",
        "server sent events",
        "sse",
    ],

    authentication: [
        "auth",
        "authentication",
        "login",
        "login system",
        "user auth",
        "oauth",
        "oauth2",
        "oauth 2.0",
        "openid",
        "openid connect",
        "oidc",
        "jwt auth",
        "jwt authentication",
        "sso",
        "single sign-on",
        "password authentication",
        "passkeys",
        "webauthn",
    ],

    authorization: [
        "authz",
        "authorization",
        "access control",
        "rbac",
        "role based access",
        "role-based access",
        "permissions",
        "permission system",
        "acl",
        "attribute based access control",
        "abac",
        "policy based access control",
        "pbac",
    ],

    "api-design": [
        "api architecture",
        "api design",
        "designing apis",
        "api best practices",
        "api versioning",
        "api gateway design",
        "api contracts",
        "api contract",
        "api documentation",
        "openapi",
        "swagger",
    ],

    // =========================
    // Database
    // =========================
    postgresql: [
        "postgres",
        "postgresql",
        "postgres db",
        "postgres database",
        "psql",
        "pg",
        "postgresql database",
        "postgres database",
        "postgres sql",
        "pgadmin",
        "postgres extensions",
        "postgres indexing",
        "postgres performance",
    ],

    mysql: [
        "mysql",
        "my sql",
        "mysql database",
        "mysql db",
        "mariadb",
        "maria db",
        "mysql server",
        "mysql optimization",
    ],

    mongodb: [
        "mongo",
        "mongodb",
        "mongo db",
        "mongodb database",
        "mongodb atlas",
        "mongo atlas",
        "nosql mongodb",
        "mongoose",
        "mongo aggregation",
    ],

    redis: [
        "redis",
        "redis cache",
        "redis db",
        "redis database",
        "in-memory database",
        "in memory store",
        "redis streams",
        "redis pubsub",
        "redis pub/sub",
        "redis queue",
        "redis caching",
    ],

    sqlite: [
        "sqlite",
        "sqlite3",
        "sqlite database",
        "embedded database",
        "local database",
    ],

    elasticsearch: [
        "elastic search",
        "elasticsearch",
        "elastic",
        "es",
        "elk",
        "elk stack",
        "elastic stack",
        "full-text search",
        "full text search",
        "logstash",
        "kibana",
    ],

    orm: [
        "orm",
        "object relational mapping",
        "object-relational mapping",
        "prisma",
        "prisma orm",
        "sequelize",
        "typeorm",
        "drizzle",
        "drizzle orm",
        "hibernate",
        "entity framework",
    ],

    "database-design": [
        "db design",
        "database design",
        "schema design",
        "database schema",
        "schema architecture",
        "data modeling",
        "data model",
        "database modeling",
        "relational modeling",
        "normalization",
        "denormalization",
    ],

    "query-optimization": [
        "sql optimization",
        "query optimization",
        "query performance",
        "database optimization",
        "index optimization",
        "slow query",
        "slow query tuning",
        "sql performance",
        "database performance",
        "execution plan",
        "query planner",
    ],

    caching: [
        "cache",
        "caching",
        "cache strategy",
        "cache layer",
        "memoization",
        "cdn caching",
        "http caching",
        "browser caching",
        "application caching",
        "distributed cache",
    ],

    // =========================
    // Cloud & DevOps
    // =========================
    docker: [
        "docker",
        "dockerfile",
        "docker container",
        "docker containers",
        "containerization",
        "containerisation",
        "docker compose",
        "docker-compose",
        "container",
        "containers",
        "container runtime",
    ],

    kubernetes: [
        "k8s",
        "kube",
        "kubernetes",
        "kubectl",
        "kubernetes cluster",
        "k8s cluster",
        "container orchestration",
        "pod",
        "pods",
        "deployment kubernetes",
        "helm",
        "helm charts",
        "kustomize",
    ],

    aws: [
        "aws",
        "amazon web services",
        "amazon aws",
        "aws cloud",
        "aws services",
        "aws infrastructure",
        "aws architecture",
        "ec2",
        "ec2 instance",
        "s3",
        "aws s3",
        "lambda",
        "aws lambda",
        "lambda aws",
        "iam",
        "aws iam",
        "vpc",
        "aws vpc",
        "rds",
        "aws rds",
        "dynamodb",
        "aws dynamodb",
        "cloudfront",
        "aws cloudfront",
        "route53",
        "route 53",
        "aws route53",
        "ecs",
        "aws ecs",
        "eks",
        "aws eks",
        "fargate",
        "aws fargate",
        "sns",
        "aws sns",
        "sqs",
        "aws sqs",
        "eventbridge",
        "aws eventbridge",
        "cloudwatch",
        "aws cloudwatch",
        "api gateway",
        "aws api gateway",
        "secrets manager",
        "aws secrets manager",
        "kms",
        "aws kms",
        "cognito",
        "aws cognito",
        "organizations",
        "aws organizations",
        "ram",
        "aws resource access manager",
        "migration",
        "aws migration",
    ],

    azure: [
        "azure",
        "microsoft azure",
        "azure cloud",
        "azure functions",
        "azure vm",
        "azure virtual machine",
        "azure storage",
        "blob storage",
        "azure sql",
        "azure devops",
        "aks",
        "azure kubernetes",
        "entra id",
        "azure ad",
        "active directory azure",
        "azure active directory",
    ],

    gcp: [
        "gcp",
        "google cloud",
        "google cloud platform",
        "gcp cloud",
        "google cloud compute",
        "compute engine",
        "gce",
        "cloud storage",
        "google cloud storage",
        "gke",
        "google kubernetes engine",
        "cloud run",
        "cloud functions",
        "bigquery",
        "pubsub",
        "google pubsub",
        "cloud sql",
        "firebase",
        "google cloud functions",
    ],

    terraform: [
        "terraform",
        "iac",
        "infrastructure as code",
        "infrastructure-as-code",
        "terraform hcl",
        "hcl",
        "tf",
        "tf modules",
        "terraform modules",
        "terraform provider",
        "terraform state",
        "terraform cloud",
    ],

    "github-actions": [
        "github actions",
        "github workflows",
        "github workflow",
        "gh actions",
        "github ci",
        "github actions ci",
        "github actions cd",
        "github runners",
        "github action runner",
    ],

    "ci-cd": [
        "ci/cd",
        "ci cd",
        "cicd",
        "continuous integration",
        "continuous deployment",
        "continuous delivery",
        "deployment pipeline",
        "build pipeline",
        "release pipeline",
        "automation pipeline",
        "devops pipeline",
    ],

    serverless: [
        "serverless",
        "faas",
        "function as a service",
        "serverless functions",
        "lambda functions",
        "cloud functions",
        "edge functions",
        "serverless architecture",
    ],

    linux: [
        "linux",
        "gnu/linux",
        "linux cli",
        "linux command line",
        "bash",
        "shell",
        "shell scripting",
        "unix",
        "ubuntu",
        "debian",
        "centos",
        "red hat",
        "rhel",
        "linux administration",
        "linux system administration",
    ],

    // =========================
    // AI / ML
    // =========================
    ai: [
        "ai",
        "artificial intelligence",
        "ai systems",
        "ai technology",
        "intelligent systems",
        "ai engineering",
        "ai development",
    ],

    "machine-learning": [
        "ml",
        "machine learning",
        "machine learning models",
        "machine learning engineering",
        "ml engineering",
        "supervised learning",
        "unsupervised learning",
        "semi-supervised learning",
        "reinforcement learning",
        "classification",
        "regression",
        "clustering",
        "feature engineering",
        "model training",
        "model inference",
    ],

    "deep-learning": [
        "dl",
        "deep learning",
        "deep neural learning",
        "neural networks",
        "neural network",
        "deep neural nets",
        "dnn",
        "cnn",
        "convolutional neural network",
        "rnn",
        "recurrent neural network",
        "lstm",
        "gru",
        "transformers",
    ],

    "generative-ai": [
        "genai",
        "gen ai",
        "generative ai",
        "generative artificial intelligence",
        "generative models",
        "generative model",
        "ai generation",
        "generative art ai",
        "text generation",
        "image generation",
        "multimodal ai",
    ],

    llms: [
        "llm",
        "llms",
        "large language model",
        "large language models",
        "language models",
        "foundation models",
        "foundation model",
        "gpt",
        "gpt models",
        "chatgpt",
        "claude",
        "gemini",
        "llm engineering",
        "llm applications",
    ],

    rag: [
        "rag",
        "retrieval augmented generation",
        "retrieval-augmented generation",
        "retrieval augmented",
        "rag pipeline",
        "rag architecture",
        "retrieval pipeline",
        "knowledge retrieval",
        "vector retrieval",
        "semantic retrieval",
    ],

    "ai-agents": [
        "ai agents",
        "ai-agent",
        "ai agents",
        "autonomous agents",
        "agentic ai",
        "agentic systems",
        "llm agents",
        "agent workflows",
        "ai agent workflows",
        "multi-agent systems",
        "multi agent",
        "agent orchestration",
        "agentic workflows",
    ],

    "prompt-engineering": [
        "prompt engineering",
        "prompt design",
        "prompting",
        "prompting techniques",
        "prompt optimization",
        "prompt tuning",
        "prompt templates",
        "system prompts",
        "few-shot prompting",
        "zero-shot prompting",
        "chain of thought prompting",
    ],

    embeddings: [
        "embeddings",
        "embedding",
        "vector embeddings",
        "text embeddings",
        "embedding models",
        "semantic embeddings",
        "sentence embeddings",
        "document embeddings",
    ],

    "vector-database": [
        "vector database",
        "vector db",
        "vectordb",
        "vector store",
        "vector search",
        "semantic search",
        "qdrant",
        "pinecone",
        "weaviate",
        "milvus",
        "chroma",
        "chroma db",
        "pgvector",
        "vector index",
    ],

    // =========================
    // Architecture
    // =========================
    "system-design": [
        "system design",
        "systems design",
        "system architecture",
        "designing systems",
        "large scale systems",
        "scalable architecture",
        "technical architecture",
        "architecture interview",
        "system design interview",
    ],

    microservices: [
        "microservice",
        "microservices",
        "microservice architecture",
        "micro services",
        "service-oriented architecture",
        "soa",
        "distributed services",
        "service architecture",
    ],

    "distributed-systems": [
        "distributed system",
        "distributed systems",
        "distributed computing",
        "distributed architecture",
        "distributed systems design",
        "distributed application",
        "distributed applications",
        "consensus",
        "distributed consensus",
        "CAP theorem",
        "cap theorem",
    ],

    "event-driven": [
        "event-driven",
        "event driven",
        "event-driven architecture",
        "event driven architecture",
        "eda",
        "event sourcing",
        "event sourcing architecture",
        "pub-sub",
        "pubsub",
        "publish subscribe",
        "asynchronous architecture",
    ],

    "message-queues": [
        "message queue",
        "message queues",
        "mq",
        "queueing system",
        "queue",
        "rabbitmq",
        "kafka",
        "apache kafka",
        "amazon sqs",
        "sqs",
        "nats",
        "activemq",
        "pubsub",
    ],

    architecture: [
        "software architecture",
        "system architecture",
        "application architecture",
        "architectural patterns",
        "architecture patterns",
        "software design",
        "technical architecture",
        "solution architecture",
    ],

    scalability: [
        "scaling",
        "scalable systems",
        "scalability",
        "horizontal scaling",
        "vertical scaling",
        "scale out",
        "scale up",
        "high scale",
        "large scale",
        "elasticity",
    ],

    "high-availability": [
        "high availability",
        "high-availability",
        "ha",
        "high availability systems",
        "uptime",
        "failover",
        "redundancy",
        "fault recovery",
        "active-active",
        "active-passive",
    ],

    "fault-tolerance": [
        "fault tolerance",
        "fault-tolerant systems",
        "fault tolerant systems",
        "resilience",
        "resiliency",
        "graceful degradation",
        "failure recovery",
        "disaster recovery",
        "retry strategy",
        "circuit breaker",
    ],

    "design-patterns": [
        "design patterns",
        "software design patterns",
        "gof patterns",
        "gang of four",
        "architectural design patterns",
        "factory pattern",
        "singleton pattern",
        "observer pattern",
        "strategy pattern",
        "repository pattern",
        "dependency injection",
        "solid principles",
    ],

    // =========================
    // Quality
    // =========================
    testing: [
        "testing",
        "software testing",
        "unit testing",
        "unit test",
        "integration testing",
        "integration test",
        "e2e testing",
        "end to end testing",
        "end-to-end testing",
        "test automation",
        "automated testing",
        "qa testing",
        "quality assurance",
        "jest",
        "vitest",
        "cypress",
        "playwright",
        "selenium",
    ],

    performance: [
        "performance",
        "performance optimization",
        "performance tuning",
        "speed optimization",
        "perf",
        "application performance",
        "web performance",
        "latency optimization",
        "throughput optimization",
        "performance engineering",
        "profiling",
    ],

    security: [
        "security",
        "application security",
        "appsec",
        "cybersecurity",
        "cyber security",
        "infosec",
        "information security",
        "secure coding",
        "security engineering",
        "web security",
        "cloud security",
        "api security",
        "owasp",
        "vulnerability",
    ],

    observability: [
        "observability",
        "observability stack",
        "telemetry",
        "opentelemetry",
        "open telemetry",
        "tracing",
        "distributed tracing",
        "metrics and logs",
        "application observability",
        "system observability",
    ],

    monitoring: [
        "monitoring",
        "app monitoring",
        "application monitoring",
        "system monitoring",
        "infrastructure monitoring",
        "metrics",
        "alerting",
        "health monitoring",
        "uptime monitoring",
        "prometheus",
        "grafana",
    ],

    logging: [
        "logging",
        "log management",
        "structured logging",
        "log aggregation",
        "application logs",
        "centralized logging",
        "log analysis",
        "elk logging",
        "logstash",
        "fluentd",
        "fluent bit",
    ],

    debugging: [
        "debugging",
        "debug",
        "troubleshooting",
        "bug fixing",
        "root cause analysis",
        "rca",
        "debugging techniques",
        "production debugging",
        "error investigation",
    ],

    refactoring: [
        "refactoring",
        "code refactoring",
        "refactor",
        "codebase cleanup",
        "technical cleanup",
        "legacy code refactoring",
        "code restructuring",
    ],

    "clean-code": [
        "clean code",
        "clean coding",
        "readable code",
        "maintainable code",
        "maintainable software",
        "code readability",
        "code simplicity",
        "clean architecture",
    ],

    "code-quality": [
        "code quality",
        "code standards",
        "code review",
        "code reviews",
        "linting",
        "static analysis",
        "sonarqube",
        "eslint",
        "prettier",
        "quality gates",
    ],

    // =========================
    // Engineering
    // =========================
    "case-study": [
        "case study",
        "case studies",
        "real-world example",
        "real world example",
        "production example",
        "postmortem",
        "post-mortem",
        "engineering case study",
        "architecture case study",
        "incident report",
    ],

    "best-practices": [
        "best practices",
        "best practice",
        "industry best practices",
        "recommended practices",
        "recommended approach",
        "engineering practices",
        "development practices",
        "coding practices",
        "guidelines",
        "standards",
        "patterns and practices",
    ],

    tutorial: [
        "tutorial",
        "tutorials",
        "how-to",
        "how to",
        "how-to guide",
        "step-by-step guide",
        "step by step guide",
        "walkthrough",
        "getting started",
        "getting started guide",
        "beginner guide",
        "implementation guide",
        "hands-on guide",
    ],

    "engineering-culture": [
        "engineering culture",
        "eng culture",
        "team culture",
        "engineering org",
        "engineering organization",
        "engineering management",
        "developer culture",
        "technical leadership",
        "engineering leadership",
    ],

    "developer-experience": [
        "developer experience",
        "developer productivity",
        "dx",
        "dev experience",
        "developer workflow",
        "developer tooling experience",
        "engineering productivity",
        "developer efficiency",
    ],

    "developer-tools": [
        "developer tools",
        "dev tools",
        "devtools",
        "tooling",
        "cli tools",
        "developer tooling",
        "build tools",
        "development tools",
        "code editor",
        "ide",
    ],

    "open-source": [
        "open source",
        "open-source",
        "open source software",
        "oss",
        "foss",
        "free and open source",
        "open source project",
        "open source projects",
        "community software",
    ],

    "product-engineering": [
        "product engineering",
        "product eng",
        "product-minded engineering",
        "product minded engineering",
        "product development",
        "software product development",
        "engineering product",
        "product-focused engineering",
    ],

    career: [
        "career",
        "career growth",
        "career advice",
        "career development",
        "developer career",
        "software engineering career",
        "engineering career",
        "job search",
        "jobs",
        "job hunting",
        "career path",
        "career progression",
        "promotion",
        "engineering promotion",
        "technical career",
    ],

    interview: [
        "interview",
        "interview prep",
        "interview preparation",
        "coding interview",
        "technical interview",
        "software engineering interview",
        "system design interview",
        "behavioral interview",
        "technical screening",
        "coding challenge",
        "coding assessment",
        "interview questions",
        "leetcode",
        "dsa interview",
    ],
};